name: Python Build and Release

on:
  pull_request: # test
    branches: [ "main" ]
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: 'Get Previous tag'
      id: previous_tag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0

    - name: Build executables
      run: |
        pyinstaller -n NidhoggCrypt ngc.py
        pyinstaller -n NidhoggCryptCli cli_ngc.py
      

    - name: Upload to Releases
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{steps.previous_tag.outputs.tag}}
        files: |
          dist/ngc.exe
          dist/cli_ngc.exe
          dist/ngc
          dist/cli_ngc

        token: ${{ secrets.GITHUB_TOKEN }}
