name: Python Build and Release

on:
  pull_request: # test
    branches: [ "main" ]
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


    - name: Build executables
      run: |
        pyinstaller --onefile ngc.py
        pyinstaller --onefile cli_ngc.py
        # Adicione outros comandos de build se necessário.
    
    - name: 'Get Previous tag'
      id: previous_tag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0
        
    - name: Upload to Releases
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{steps.previous_tag.outputs.tag}}
        files: |
          dist/ngc.exe  # Caminho para o executável do Windows
          dist/cli_ngc.exe  # Caminho para o executável do Windows CLI
          dist/ngc  # Caminho para o executável do Linux
          dist/cli_ngc  # Caminho para o executável do Linux CLI
          # Adicione outros arquivos gerados pelo build, se houver.
        token: ${{ secrets.GITHUB_TOKEN }}