
name: Pyinstaller publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          python-version: ["3.9","3.10"]
          os: [ubuntu-latest, macos-latest, windows-latest]

      steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install UPX compressor
        run: sudo apt-get install -y upx
      - name: Pyinstaller run
        run: |
          pyinstaller -n NidhoggCrypt ngc.py
          pyinstaller -n NidhoggCryptCli cli_ngc.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: NidhoggCrypt-${{ matrix.os}}-${{ matrix.python-version }}
          path: dist/NidhoggCrypt/
          if-no-files-found: error
          retention-days: 30

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: NidhoggCryptCli-${{ matrix.os}}-${{ matrix.python-version }}
          path: dist/NidhoggCryptCli/
          if-no-files-found: error
          retention-days: 30